import type { AgentProvider } from "../../model/index.js";
import type { SnapshotStorage, Logger } from "@strands-agents/sdk";
import type { APIGatewayProxyEventV2, APIGatewayProxyResultV2, Context } from "aws-lambda";

export interface LambdaAdapterOptions {
  /** Absolute path to the docs directory to index. Falls back to LITMDX_AGENT_DOCS_DIR env var. */
  docsDir?: string;
  /**
   * URL of the `docs-index.json` generated by `litmdx build`.
   * When provided, the index is fetched from the live docs site instead of
   * reading the local docs directory. Takes precedence over `docsDir`.
   * Example: 'https://my-docs.example.com/docs-index.json'
   */
  docsIndexUrl?: string;
  provider: AgentProvider;
  apiKey?: string;
  model?: string;
  systemPrompt?: string;
  windowSize?: number;
  /**
   * S3 session storage shorthand. Constructs an S3Storage without manual imports.
   * Alternatively set LITMDX_AGENT_S3_BUCKET (+ optionally LITMDX_AGENT_S3_REGION,
   * LITMDX_AGENT_S3_PREFIX or AWS_REGION) env vars.
   * Takes precedence over `storage`.
   */
  s3Sessions?: { bucket: string; prefix?: string; region?: string };
  /** Custom SnapshotStorage. Use `s3Sessions` for the S3Storage shorthand. */
  storage?: SnapshotStorage;
  /**
   * Origins allowed by CORS.
   * Use '*' to allow all origins (fine for public docs).
   */
  allowedOrigins?: string[];
  /**
   * When true (default), the handler uses Lambda Response Streaming.
   * When false, the full response is buffered and returned as JSON.
   */
  streaming?: boolean;
  /**
   * Enable the official Strands SDK logs described in the observability docs.
   *
   * - `true`: send SDK logs to `console`
   * - `Logger`: use a custom logger implementation (for example Pino/Winston)
   * - `false` / `undefined`: leave SDK logging unconfigured
   */
  sdkLogging?: boolean | Logger;
}

export type LambdaHandler = (
  event: APIGatewayProxyEventV2,
  context: Context,
) => Promise<APIGatewayProxyResultV2>;
