import type { AgentProvider } from "../../model/index.js";
import type { SnapshotStorage, McpClient, Logger } from "@strands-agents/sdk";
import type { DocsIndex } from "../../indexer/index.js";
import type { z } from "zod";
import type { SubAgentConfig } from "../../session/types.js";

export interface NodeHttpAdapterOptions {
  /**
   * Pre-built DocsIndex. When provided, `docsDir` and `docsIndexUrl` are ignored.
   */
  index?: DocsIndex;
  /** Absolute path to the docs directory to index. */
  docsDir: string;
  /**
   * URL of the `docs-index.json` generated by `litmdx build`.
   * When provided, the index is fetched from the live docs site instead of
   * reading the local docs directory. Takes precedence over `docsDir`.
   * Example: 'https://my-docs.example.com/docs-index.json'
   */
  docsIndexUrl?: string;
  provider: AgentProvider;
  apiKey?: string;
  model?: string;
  /** Port to listen on. Default: 8000. */
  port?: number;
  /** Host to bind to. Default: '0.0.0.0' (all interfaces). */
  host?: string;
  /** Project title used in the default system prompt. Defaults to the docs directory basename. */
  projectTitle?: string;
  systemPrompt?: string;
  windowSize?: number;
  sessionsDir?: string;
  /**
   * S3 session storage shorthand. Constructs an S3Storage without manual imports.
   * Takes precedence over `sessionsDir`. Ignored when `storage` is provided.
   */
  s3Sessions?: { bucket: string; prefix?: string; region?: string };
  /** Custom SnapshotStorage (e.g. S3Storage). Takes precedence over sessionsDir. */
  storage?: SnapshotStorage;
  /**
   * Origins allowed by CORS.
   * Automatically includes 'http://localhost:5173' and 'http://127.0.0.1:5173'.
   */
  allowedOrigins?: string[];
  /**
   * External MCP servers to use as additional tool sources.
   * Each McpClient is connected on first request and its tools are made available
   * to the agent alongside the built-in `list_pages`, `get_page`, `search_docs` tools.
   *
   * @example
   * ```typescript
   * import { McpClient } from '@strands-agents/sdk';
   * import { SSEClientTransport } from '@modelcontextprotocol/sdk/client/sse.js';
   *
   * createNodeHttpServer({
   *   mcpClients: [
   *     new McpClient({ transport: new SSEClientTransport(new URL('http://localhost:3001/sse')) })
   *   ],
   * });
   * ```
   */
  mcpClients?: McpClient[];
  /**
   * Enable @litmdx/agent lifecycle hooks for structured console logging.
   * Logs tool calls (with timing), model calls, and invocation lifecycle events.
   * Defaults to `true`.
   */
  logging?: boolean;
  /**
   * Enable the official Strands SDK logs described in the observability docs.
   *
   * - `true`: send SDK logs to `console`
   * - `Logger`: use a custom logger implementation (for example Pino/Winston)
   * - `false` / `undefined`: leave SDK logging unconfigured
   *
   * This is separate from `logging`, which controls the local `LoggingPlugin`.
   */
  sdkLogging?: boolean | Logger;
  /**
   * Conversation history management strategy.
   * - `'sliding-window'` (default): discards oldest messages when context is full.
   * - `'summarizing'`: summarizes oldest messages with a model call instead of discarding.
   * @default 'sliding-window'
   */
  conversationManager?: "sliding-window" | "summarizing";
  /**
   * Whether to truncate large tool results to fit the model's context window.
   * Only applies when `conversationManager` is `'sliding-window'`.
   * @default true
   */
  shouldTruncateResults?: boolean;
  /**
   * Ratio of older messages to summarize on context overflow. Clamped to [0.1, 0.8].
   * Only applies when `conversationManager` is `'summarizing'`.
   * @default 0.3
   */
  summaryRatio?: number;
  /**
   * Minimum number of recent messages to always preserve.
   * Only applies when `conversationManager` is `'summarizing'`.
   * @default 10
   */
  preserveRecentMessages?: number;
  /**
   * Zod schema for structured output (agent-level default).
   * When set, every agent invocation coerces the model response into this
   * schema and exposes the result via `AgentResult.structuredOutput`.
   * The `/chat` endpoint returns `structuredOutput` alongside `response`.
   * The `/chat/stream` endpoint emits a `[STRUCTURED_OUTPUT] {...}` SSE
   * event before `[DONE]` when structured output is available.
   */
  structuredOutputSchema?: z.ZodSchema;
  /**
   * Maximum number of retry attempts when the model returns a throttling error.
   * Uses exponential backoff starting at `retryDelayMs`.
   * Set to 0 to disable. Defaults to 3.
   */
  maxRetries?: number;
  /**
   * Base delay in milliseconds before the first retry.
   * Doubles with each subsequent attempt. Defaults to 1000.
   */
  retryDelayMs?: number;
  /**
   * Enable the `notebook` vended tool. Gives the agent a persistent scratchpad
   * it can read and write across invocations. Persists automatically with the
   * session snapshot. Works in all environments.
   * @default false
   */
  notebook?: boolean;
  /**
   * Sub-agents to register as tools for an orchestrator agent.
   *
   * When non-empty, the session enters **orchestrator mode**: the main agent's
   * tool list is replaced by these sub-agent tools so the orchestrator
   * delegates domain tasks to specialists. The built-in tools (`search_docs`,
   * `get_page`, `list_pages`) are available to each sub-agent by default.
   *
   * @see {@link SubAgentConfig}
   * @example
   * ```typescript
   * subAgents: [
   *   { name: 'docs_specialist', description: 'Search and retrieve documentation pages.' },
   *   { name: 'code_specialist', description: 'Write working code examples.', systemPrompt: '...' },
   * ]
   * ```
   */
  subAgents?: SubAgentConfig[];
  /**
   * Custom system prompt for the orchestrator agent.
   *
   * Only relevant when `subAgents` is non-empty. When omitted, a default
   * orchestrator prompt is generated automatically — routing constraints for
   * `docs_specialist` and all registered sub-agents are included.
   * You only need this field to completely override that generated prompt.
   */
  orchestratorSystemPrompt?: string;
}
