import type { AgentProvider } from "../../model/index.js";
import type { SnapshotStorage, Logger } from "@strands-agents/sdk";
import type { DocsIndex } from "../../indexer/index.js";
import type { z } from "zod";

export interface HonoAdapterOptions {
  /**
   * Pre-built DocsIndex. When provided, `docsDir` and `docsIndexUrl` are ignored.
   * Required on runtimes without `node:fs` (Cloudflare Workers).
   */
  index?: DocsIndex;
  /**
   * Absolute path to the docs directory. Used when `index` is not provided.
   * Not available on Cloudflare Workers — use `index` or `docsIndexUrl` instead.
   */
  docsDir?: string;
  /**
   * URL of the `docs-index.json` generated by `litmdx build`.
   * The index is fetched from the live docs site at first request.
   * Ideal for Cloudflare Workers — no need to bundle the docs or run a pre-build step.
   * Takes precedence over `docsDir`. Ignored when `index` is provided.
   * Example: 'https://my-docs.example.com/docs-index.json'
   */
  docsIndexUrl?: string;
  provider: AgentProvider;
  /** API key. On Cloudflare Workers, pass via runtime env instead. */
  apiKey?: string;
  model?: string;
  systemPrompt?: string;
  windowSize?: number;
  /**
   * Session snapshot storage backend.
   *
   * Defaults to `MemoryStorage` (in-process only — sessions are lost when the
   * Worker instance is recycled or a new instance handles the request).
   *
   * For durable sessions on Cloudflare Workers, use one of the CF-native
   * backends exported from this adapter:
   *
   *   import { KVStorage, R2Storage } from '@litmdx/agent/adapters/hono';
   *
   *   storage: new KVStorage(env.SESSIONS_KV)   // KV Namespace binding
   *   storage: new R2Storage(env.SESSIONS_R2)   // R2 Bucket binding
   *
   * For Node.js (non-Worker) Hono deployments you can also use `FileStorage`
   * or `S3Storage` from `@strands-agents/sdk`.
   */
  storage?: SnapshotStorage;
  /**
   * Origins allowed by CORS.
   * Default: '*' (public docs — safe since there is no user data).
   * Restrict when the agent holds sensitive session data.
   */
  allowedOrigins?: string | string[];
  /**
   * External MCP servers to use as additional tool sources.
   * Each McpClient is connected on first request and its tools are made available
   * to the agent alongside the built-in tools.
   */
  mcpClients?: import("@strands-agents/sdk").McpClient[];
  /**
   * Enable @litmdx/agent lifecycle hooks for structured console logging.
   * Logs tool calls (with timing), model calls, and invocation lifecycle events.
   * Defaults to `true`.
   */
  logging?: boolean;
  /**
   * Enable the official Strands SDK logs described in the observability docs.
   *
   * - `true`: send SDK logs to `console`
   * - `Logger`: use a custom logger implementation (for example Pino/Winston)
   * - `false` / `undefined`: leave SDK logging unconfigured
   *
   * This is separate from `logging`, which controls the local `LoggingPlugin`.
   */
  sdkLogging?: boolean | Logger;
  /**
   * Conversation history management strategy.
   * - `'sliding-window'` (default): discards oldest messages when context is full.
   * - `'summarizing'`: summarizes oldest messages with a model call instead of discarding.
   * @default 'sliding-window'
   */
  conversationManager?: "sliding-window" | "summarizing";
  /**
   * Whether to truncate large tool results to fit the model's context window.
   * Only applies when `conversationManager` is `'sliding-window'`.
   * @default true
   */
  shouldTruncateResults?: boolean;
  /**
   * Ratio of older messages to summarize on context overflow. Clamped to [0.1, 0.8].
   * Only applies when `conversationManager` is `'summarizing'`.
   * @default 0.3
   */
  summaryRatio?: number;
  /**
   * Minimum number of recent messages to always preserve.
   * Only applies when `conversationManager` is `'summarizing'`.
   * @default 10
   */
  preserveRecentMessages?: number;
  /**
   * Zod schema for structured output (agent-level default).
   * When set, every agent invocation coerces the model response into this
   * schema and exposes the result via `AgentResult.structuredOutput`.
   * The `/chat` endpoint returns `structuredOutput` alongside `response`.
   * The `/chat/stream` endpoint emits a `[STRUCTURED_OUTPUT] {...}` SSE
   * event before `[DONE]` when structured output is available.
   */
  structuredOutputSchema?: z.ZodSchema;
  /**
   * Maximum number of retry attempts when the model returns a throttling error.
   * Uses exponential backoff starting at `retryDelayMs`.
   * Set to 0 to disable. Defaults to 3.
   */
  maxRetries?: number;
  /**
   * Base delay in milliseconds before the first retry.
   * Doubles with each subsequent attempt. Defaults to 1000.
   */
  retryDelayMs?: number;
  /**
   * Enable the `notebook` vended tool. Gives the agent a persistent scratchpad
   * it can read and write across invocations. Persists automatically with the
   * session snapshot. Works in all environments including Cloudflare Workers.
   * @default false
   */
  notebook?: boolean;
}
